{{/*
Expand the name of the chart.
*/}}
{{- define "sentinelx.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "sentinelx.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{- define "sentinelx.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "sentinelx.namespace" -}}
{{- .Values.namespace.name }}
{{- end }}

{{- define "sentinelx.labels" -}}
helm.sh/chart: {{ include "sentinelx.chart" . }}
{{ include "sentinelx.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{- define "sentinelx.selectorLabels" -}}
app.kubernetes.io/name: {{ include "sentinelx.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- define "sentinelx.componentLabels" -}}
{{ include "sentinelx.selectorLabels" . }}
app.kubernetes.io/component: {{ .component }}
{{- end }}

{{- define "sentinelx.image" -}}
{{- $registry := .Values.global.imageRegistry -}}
{{- $repo := .repository -}}
{{- $tag := .tag | default "latest" -}}
{{- if $registry -}}
{{- printf "%s/%s:%s" $registry $repo $tag -}}
{{- else -}}
{{- printf "%s:%s" $repo $tag -}}
{{- end }}
{{- end }}

{{- define "sentinelx.secretName" -}}
{{- printf "%s-secrets" (include "sentinelx.fullname" .) }}
{{- end }}

{{- define "sentinelx.configMapName" -}}
{{- printf "%s-config" (include "sentinelx.fullname" .) }}
{{- end }}

{{- define "sentinelx.lookupSecretKey" -}}
{{- $root := .root -}}
{{- $key := .key -}}
{{- $existing := lookup "v1" "Secret" (include "sentinelx.namespace" $root) (include "sentinelx.secretName" $root) -}}
{{- if and $existing $existing.data (index $existing.data $key) -}}
{{- index $existing.data $key | b64dec -}}
{{- end -}}
{{- end }}

{{/*
Resolve a secret value: explicit values > existing cluster Secret > auto-generate (when enabled).
lookup requires a live cluster on install/upgrade; helm template falls back to generation.
*/}}
{{- define "sentinelx.resolveSecret" -}}
{{- $root := .root -}}
{{- $key := .key -}}
{{- $provided := .provided -}}
{{- $length := .length | default 32 -}}
{{- $failKey := .failKey -}}
{{- if $provided -}}
{{- $provided -}}
{{- else if not $root.Values.secrets.autoGenerate -}}
{{- required (printf "secrets.%s is required when secrets.autoGenerate is false" $failKey) $provided -}}
{{- else -}}
{{- $fromCluster := include "sentinelx.lookupSecretKey" (dict "root" $root "key" $key) -}}
{{- if $fromCluster -}}
{{- $fromCluster -}}
{{- else -}}
{{- randAlphaNum (int $length) -}}
{{- end -}}
{{- end -}}
{{- end }}

{{- define "sentinelx.jwtSecretKey" -}}
{{- include "sentinelx.resolveSecret" (dict "root" . "key" "JWT_SECRET_KEY" "provided" .Values.secrets.jwtSecretKey "length" (.Values.secrets.jwtSecretKeyLength | default 64) "failKey" "jwtSecretKey") -}}
{{- end }}

{{- define "sentinelx.dbPassword" -}}
{{- $provided := .Values.secrets.dbPassword | default .Values.postgresql.auth.password -}}
{{- include "sentinelx.resolveSecret" (dict "root" . "key" "DB_PASSWORD" "provided" $provided "length" (.Values.secrets.dbPasswordLength | default 32) "failKey" "dbPassword") -}}
{{- end }}

{{- define "sentinelx.defaultAdminPassword" -}}
{{- if not .Values.secrets.autoGenerateDefaultAdmin -}}
{{- .Values.secrets.defaultAdminPassword -}}
{{- else -}}
{{- $provided := .Values.secrets.defaultAdminPassword -}}
{{- include "sentinelx.resolveSecret" (dict "root" . "key" "DEFAULT_ADMIN_PASSWORD" "provided" $provided "length" (.Values.secrets.defaultAdminPasswordLength | default 16) "failKey" "defaultAdminPassword") -}}
{{- end -}}
{{- end }}

{{- define "sentinelx.dbUser" -}}
{{- .Values.secrets.dbUser | default .Values.postgresql.auth.username -}}
{{- end }}

{{- define "sentinelx.dbHost" -}}
{{- if .Values.backend.externalDbHost -}}
{{- .Values.backend.externalDbHost -}}
{{- else if .Values.postgresql.enabled -}}
{{- .Values.postgresql.serviceName -}}
{{- else -}}
{{- required "backend.externalDbHost is required when postgresql.enabled=false" .Values.backend.externalDbHost -}}
{{- end }}
{{- end }}

{{- define "sentinelx.redisHost" -}}
{{- if .Values.backend.externalRedisHost -}}
{{- .Values.backend.externalRedisHost -}}
{{- else if .Values.redis.enabled -}}
{{- .Values.redis.serviceName -}}
{{- else -}}
{{- required "backend.externalRedisHost is required when redis.enabled=false" .Values.backend.externalRedisHost -}}
{{- end }}
{{- end }}

{{- define "sentinelx.postgresql.fullname" -}}
{{- printf "%s-postgresql" (include "sentinelx.fullname" .) }}
{{- end }}

{{- define "sentinelx.postgresql.headlessServiceName" -}}
{{- printf "%s-headless" .Values.postgresql.serviceName }}
{{- end }}

{{- define "sentinelx.redis.fullname" -}}
{{- printf "%s-redis" (include "sentinelx.fullname" .) }}
{{- end }}

{{- define "sentinelx.redis.headlessServiceName" -}}
{{- printf "%s-headless" .Values.redis.serviceName }}
{{- end }}

{{- define "sentinelx.backend.fullname" -}}
{{- printf "%s-backend" (include "sentinelx.fullname" .) }}
{{- end }}

{{- define "sentinelx.frontend.fullname" -}}
{{- printf "%s-frontend" (include "sentinelx.fullname" .) }}
{{- end }}
