{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinelx.redis.headlessServiceName" . }}
  namespace: {{ include "sentinelx.namespace" . }}
  labels:
    {{- include "sentinelx.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  selector:
    {{- include "sentinelx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
  namespace: {{ include "sentinelx.namespace" . }}
  labels:
    {{- include "sentinelx.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "sentinelx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
{{- end }}
