apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinelx.secretName" . }}
  namespace: {{ include "sentinelx.namespace" . }}
  labels:
    {{- include "sentinelx.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ include "sentinelx.dbUser" . | quote }}
  DB_PASSWORD: {{ include "sentinelx.dbPassword" . | quote }}
  JWT_SECRET_KEY: {{ required "secrets.jwtSecretKey is required" .Values.secrets.jwtSecretKey | quote }}
  {{- if .Values.secrets.defaultAdminPassword }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.secrets.defaultAdminPassword | quote }}
  {{- end }}
